/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisBackground: typeof import('./components/AnalysisBackground.vue')['default']
    BookHero: typeof import('./components/BookHero.vue')['default']
    CopyErrorMessage: typeof import('./components/CopyErrorMessage.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GalaxyBackground: typeof import('./components/GalaxyBackground.vue')['default']
    GridHorizon: typeof import('./components/GridHorizon.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    NeuralBackground: typeof import('./components/NeuralBackground.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TableOfContents: typeof import('./components/TableOfContents.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    TypeWriter: typeof import('./components/TypeWriter.vue')['default']
  }
}

// For TSX support
declare global {
  const AnalysisBackground: typeof import('./components/AnalysisBackground.vue')['default']
  const BookHero: typeof import('./components/BookHero.vue')['default']
  const CopyErrorMessage: typeof import('./components/CopyErrorMessage.vue')['default']
  const Footer: typeof import('./components/Footer.vue')['default']
  const GalaxyBackground: typeof import('./components/GalaxyBackground.vue')['default']
  const GridHorizon: typeof import('./components/GridHorizon.vue')['default']
  const Header: typeof import('./components/Header.vue')['default']
  const NeuralBackground: typeof import('./components/NeuralBackground.vue')['default']
  const Sidebar: typeof import('./components/Sidebar.vue')['default']
  const TableOfContents: typeof import('./components/TableOfContents.vue')['default']
  const ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  const TypeWriter: typeof import('./components/TypeWriter.vue')['default']
}